### ISSUE TITLE
Worker Failing when not acquiring lock file.

### ISSUE THREAD

**Issue by lucaspanayiotou** [OasisLMF/ktools#21]
We have recently been experiencing the following error where ktool is unable to acquire the "resource lock" and is in turn hard failing. Should the correct behavior to simply be to poll until the resource lock is acquired?
Running worker version: coreoasis/model_execution_worker:0.394.0

Python error below. 

[2018-10-30 14:27:25,212: INFO/ForkPoolWorker-1] STARTED: src.model_execution_worker.tasks.start_analysis
[2018-10-30 14:27:25,216: INFO/ForkPoolWorker-1] Source tag = 705; Analysis tag: test
[2018-10-30 14:27:25,216: INFO/ForkPoolWorker-1] Model supplier - version = GuyCarpenter DEHL
[2018-10-30 14:27:25,217: INFO/ForkPoolWorker-1] Setting up analysis working directory
[2018-10-30 14:27:25,222: INFO/ForkPoolWorker-1] Working directory = /var/oasis/working/test_705_4fc5f5c0bf754bedbee27e5bd586362a
[2018-10-30 14:27:25,222: INFO/ForkPoolWorker-1] STARTED: oasislmf.model_execution.runner.run
[2018-10-30 14:27:30,033: INFO/ForkPoolWorker-1] COMPLETED: oasislmf.model_execution.runner.run in 4.81s
[2018-10-30 14:27:30,040: INFO/ForkPoolWorker-1] Output location = f80fef42a5f748b994925ac16ae89747
[2018-10-30 14:27:30,040: INFO/ForkPoolWorker-1] COMPLETED: src.model_execution_worker.tasks.start_analysis in 4.83s
[2018-10-30 14:27:30,049: INFO/ForkPoolWorker-1] Task run_analysis[6bb6b8bf-2412-4f99-939f-e59ffaa457f7] succeeded in 4.864073348s: 'f80fef42a5f748b994925ac16ae89747'
[2018-10-31 09:13:03,442: INFO/MainProcess] Received task: run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f]
[2018-10-31 09:13:03,557: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2018-10-31 09:13:03,746: INFO/MainProcess] Received task: run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f]  ETA:[2018-10-31 09:13:13.595356+00:00]
[2018-10-31 09:13:03,785: WARNING/ForkPoolWorker-1] Failed operation _store_result.  Retrying 2 more times.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 53, in _inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 107, in _store_result
    task = list(session.query(Task).filter(Task.task_id == task_id))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 766, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 713, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (error(32, 'Broken pipe'))") [SQL: u'SELECT celery_taskmeta.id AS celery_taskmeta_id, celery_taskmeta.task_id AS celery_taskmeta_task_id, celery_taskmeta.status AS celery_taskmeta_status, celery_taskmeta.result AS celery_taskmeta_result, celery_taskmeta.date_done AS celery_taskmeta_date_done, celery_taskmeta.traceback AS celery_taskmeta_traceback \nFROM celery_taskmeta \nWHERE celery_taskmeta.task_id = %(task_id_1)s'] [parameters: {u'task_id_1': 'bb2463f5-16a1-467d-a942-a7ab2ff7647f'}] (Background on this error at: http://sqlalche.me/e/e3q8)
[2018-10-31 09:13:03,804: INFO/ForkPoolWorker-1] Task run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f] retry: Retry in 10s
[2018-10-31 09:13:13,861: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2018-10-31 09:13:13,866: INFO/MainProcess] Received task: run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f]  ETA:[2018-10-31 09:13:23.862599+00:00]
[2018-10-31 09:13:13,872: INFO/ForkPoolWorker-1] Task run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f] retry: Retry in 10s
[2018-10-31 09:13:23,869: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2018-10-31 09:13:23,873: INFO/MainProcess] Received task: run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f]  ETA:[2018-10-31 09:13:33.870280+00:00]
[2018-10-31 09:13:23,876: INFO/ForkPoolWorker-1] Task run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f] retry: Retry in 10s
[2018-10-31 09:13:33,874: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2018-10-31 09:13:33,883: WARNING/ForkPoolWorker-1] /usr/local/lib/python2.7/dist-packages/pymysql/cursors.py:170: Warning: (1300, "Invalid utf8mb4 character string: '80027D'")
  result = self._query(query)
[2018-10-31 09:13:33,885: ERROR/ForkPoolWorker-1] Task run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f] raised unexpected: MaxRetriesExceededError(u"Can't retry run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f] args:(u'8a9bea89e3504e0980bd35a70022399e', [{u'analysis_settings': {u'gul_summaries': [{u'id': 1, u'aalcalc': True}], u'source_tag': u'test', u'il_summaries': [], u'analysis_tag': u'717', u'number_of_samples': 1, u'model_version_id': u'DEHL', u'module_supplier_id': u'GuyCarpenter', u'gul_threshold': 0, u'gul_output': True, u'exposure_location': u'L:', u'prog_id': 1052, u'model_settings': {u'event_set': u'Combined', u'event_occurrence_id': u'Combined'}}}]) kwargs:{}",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "src/model_execution_worker/tasks.py", line 86, in start_analysis_task
    raise self.retry(countdown=retry_countdown_in_secs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 670, in retry
    self.name, request.id, S.args, S.kwargs))
MaxRetriesExceededError: Can't retry run_analysis[bb2463f5-16a1-467d-a942-a7ab2ff7647f] args:(u'8a9bea89e3504e0980bd35a70022399e', [{u'analysis_settings': {u'gul_summaries': [{u'id': 1, u'aalcalc': True}], u'source_tag': u'test', u'il_summaries': [], u'analysis_tag': u'717', u'number_of_samples': 1, u'model_version_id': u'DEHL', u'module_supplier_id': u'GuyCarpenter', u'gul_threshold': 0, u'gul_output': True, u'exposure_location': u'L:', u'prog_id': 1052, u'model_settings': {u'event_set': u'Combined', u'event_occurrence_id': u'Combined'}}}]) kwargs:{}

**Comment by mpinkerton-oasis** [comment]
Configuration error
